spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
