server:
  port: 8081

spring:
  application:
    name: User-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: admin
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
